INSERT INTO users (name, age) VALUES ('Bill', 40);
INSERT INTO users (name, age) VALUES ('Bob', 38);
INSERT INTO users (name, age) VALUES ('George', 30);
INSERT INTO users (name, age) VALUES ('Jim', 28);
INSERT INTO users (name, age) VALUES ('Michael', 67);
INSERT INTO users (name, age) VALUES ('Chris', 21);
INSERT INTO users (name, age) VALUES ('Luke', 25);
INSERT INTO users (name, age) VALUES ('Doug', 29);
INSERT INTO users (name, age) VALUES ('Fred', 40);
INSERT INTO users (name, age) VALUES ('Logan', 44);
INSERT INTO users (name, age) VALUES ('Eric', 39);
INSERT INTO users (name, age) VALUES ('Noah', 24);
INSERT INTO users (name, age) VALUES ('Buffy', 69);
INSERT INTO users (name, age) VALUES ('Stephanie', 88);
INSERT INTO users (name, age) VALUES ('Serena', 90);
INSERT INTO users (name, age) VALUES ('Don', 99);
INSERT INTO users (name, age) VALUES ('Dolly', 35);
INSERT INTO users (name, age) VALUES ('Dawn', 22);
INSERT INTO users (name, age) VALUES ('Heather', 25);
INSERT INTO users (name, age) VALUES ('Jessica', 26);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('a', 'a', 100, 'a', 'a');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('b', 'b', 200, 'b', 'b');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('c', 'c', 300, 'c', 'c');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('d', 'd', 500, 'd', 'd');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('e', 'e', 1000, 'e', 'e');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('f', 'f', 1100, 'f', 'f');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('g', 'g', 1200, 'g', 'g');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('h', 'h', 1400, 'h', 'h');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('i', 'i', 1111, 'i', 'i');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('j', 'j', 666, 'j', 'j');
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 2, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 5, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 6, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 9, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 11, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 12, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 13, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 14, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 15, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 16, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 17, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 20, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (123, 5, 10);



